server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api/docs

spring:
  application:
    name: cinema
    security:
      jwt:
        secret-key: "54cdf7c1f3b6489d8c6f6e562f75cad75a695a941a211ca8ddc476fcb6bd3848"
        expiration: 14400000 # 1000 * 60 * 60 * 4
        refresh-token:
          expiration: 86400000 # 1000 * 60 * 60 * 24
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

